spring:
  application:
    name: ${APP_NAME}
  profiles:
    active:
      - ${ENV}
server:
  port: ${APP_PORT}
  ssl:
    enabled: true
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWD}

logging:
  level:
    com.maat.bestbuy.integration: debug
    org.springframework: debug

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_SERVICE_PROPERTIES}
jasypt:
  encryptor:
    password: ${APP_SEC_PASSWD}