spring:
  application:
    name: mt1-cloud-config
  profiles:
    active:
      - development
server:
  port: 60143
  ssl:
    enabled: true
    key-store: C:/Users/A1187557/Documents/SSL/keystore.jks
    key-store-password: ${KEYSTORE_PASSWD}

logging:
  level:
    com.maat.bestbuy.integration: debug
    org.springframework: debug

spring:
  cloud:
    config:
      server:
        git:
          uri: file:\\\C:\Users\A1187557\Documents\git-local-repo\service-properties\