spring:
  application:
    name: ${APP_NAME}
  profiles:
    active:
      - ${ENV}
server:
  port: ${APP_PORT}
  ssl:
    enabled: true
    key-store: C:/Users/A1187557/Documents/SSL/keystore.jks
    key-store-password: ENC(bvyUqgivD+D5yK7PskZcKMNV/ufJaTVM)

logging:
  level:
    com.maat.bestbuy.integration: debug
    org.springframework: debug

spring:
  cloud:
    config:
      server:
        git:
          uri: file:\\\C:\Users\A1187557\Documents\git-local-repo\service-properties\
jasypt:
  encryptor:
    password: ${APP_SEC_PASSWD}